package com.SistemaDegestionMedica.infrastructure.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import com.SistemaDegestionMedica.config.HexaSingleton;

public class ConnMySql implements ConnectionDb {
    
    @Override
    public Connection getConexion() throws SQLException {
        HexaSingleton config = HexaSingleton.INSTANCIA;
        String url = config.get("db.url");
        String usuario = config.get("db.user");
        String password = config.get("db.password");

        return DriverManager.getConnection(url, usuario, password);
    }
    
    @Override
    public boolean testConnection() {
        try (Connection connection = getConexion()) {
            return connection != null && !connection.isClosed();
        } catch (SQLException e) {
            System.err.println("Error al probar la conexión: " + e.getMessage());
            return false;
        }
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        Connection connection = getConexion();
        return connection.prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        Connection connection = getConexion();
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public Statement createStatement() throws SQLException {
        Connection connection = getConexion();
        return connection.createStatement();
    }
}